# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: ismi_wazuh:latest
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp" #agent udp
      - "1515:1515" #agent tcp
      - "514:514/udp" #syslog
      - "55000:55000" #api
    depends_on:
      - logstash
  logstash:
    image: ismi_logstash:latest
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: ismi_elasticsearch:latest
    hostname: elasticsearch
    restart: always
    ports:
      - "9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  kibana:
    image: ismi_kibana:latest
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: ismi_nginx:latest
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
  openaudit:
    image: ismi_openaudit
    hostname: openaudit
    restart: always
  mindmeld:
    image: ismi_mindmeld
    hostname: mindmeld
    restart: always
  dradis:
    image: ismi_dradis
    hostname: dradis
    restart: always
    ports:
      - "3000:3000"
    