# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.8.2_6.5.4
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
    networks:
      - default
  logstash:
    image: wazuh/wazuh-logstash:3.8.2_6.5.4
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
    networks:
      - default
  elasticsearch:
    image: 374e0fdbeff3737901b0fb4a1747f891dd3f282a870034eb6545d68668009780
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    networks:
      - default
  kibana:
    image: wazuh/wazuh-kibana:3.8.2_6.5.4
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    networks:
      - default
  nginx:
    image: b2ce93fce0dfd40c2339c4a380bd1ff2b65687533dafd89273db0137b60503e5
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
  mongodb:
    image: a170dbb6eb2a2d6344eed092664eee7de129d0f29c8c93bd9856ef4ef9440a9f 
    restart: always
    command: /usr/bin/mongod --smallfiles --config /etc/mongod.conf
    volumes:
      - ismi_mongodb:/var/lib/mongo
  rabbitmq:
    image: rabbitmq
    restart: always
    command: rabbitmq-server
    volumes:
      - ismi_rabbitmq:/var/lib/rabbitmq
    # ports:
    #   - 5672:5672
    #   - 15672:15672 # Admin interface
    networks:
      - default
      
volumes:
  ismi_mongodb:
    driver: local
  ismi_rabbitmq:
    driver: local